services:
  playwright-test:
    image: work-recorder-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test
    volumes:
      - ./playwright-report/:/app/playwright-report/
      - ./test-results/:/app/test-results/
